url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Polychrome" # the name of your site, e.g. ACME Corp.

collections_dir: content
collections:
  authors:
  indexes:
  races:
    output: true
    permalink: /races/:path/
  subraces:
    output: true
    permalink: /subraces/:path/
  classes:
    output: true
    permalink: /classes/:path/
  subclasses:
    output: true
    permalink: /subclasses/:path/
  backgrounds:
    output: true
    permalink: /backgrounds/:path/
  feats:
    output: true
    permalink: /feats/:path/
  equipment:
    output: true
    permalink: /equipment/:path/
  spells:
    output: true
    permalink: /spells/:path/
  gods:
    output: true
    permalink: /gods/:path/
  locations:
    output: true
    permalink: /locations/:path/
  monsters:
    output: true
    permalink: /monsters/:path/
  traps:
    output: true
    permalink: /traps/:path/
  rules:
    output: true
    permalink: /rules/:path/
  weapons:
    output: true
    permalink: /equipment/weapons/:path/
  armor:
    output: true
    permalink: /equipment/armor/:path/
  items:
    output: true
    permalink: /equipment/items/:path/
  packs:
    output: true
    permalink: /equipment/packs/:path/